[package]
name = "cel-rs-macros"
version = "0.1.0"
edition = "2021"
description = "Procedural macros for cel-rs"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
cel-parser = { path = "../cel-parser" } 
