[package]
name = "cel-rs"
version = "0.1.0"
edition = "2024"
description = "A stack-based runtime for developing domain specific languages"

[dependencies]
anyhow = "1.0"
typenum = "1.18.0"
cel-rs-macros = { path = "./cel-rs-macros" }

[workspace]
members = [
    ".",
    "cel-rs-macros"
]
