[package]
name = "begin"
version = "0.1.0"
edition = "2024"
description = "Cross-platform property model development environment"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop", "dep:rfd", "dep:notify", "adam-web-ui/desktop"]
web = ["dioxus/web"]
playground = []

[dependencies]
dioxus = { version = "0.7.10", features = [] }
futures-channel = "0.3"
futures-util = "0.3"
adam-rs = { path = "../adam-rs" }
adam-web-ui = { path = "../adam-web-ui" }
cel-runtime = { path = "../cel-runtime" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
indexmap = "2"
anyhow = "1"
cel-parser = { path = "../cel-parser" }
cel-std = { path = "../cel-std" }
adam-lang = { path = "../adam-lang" }
rfd = { version = "0.17.2", optional = true }
notify = { version = "8.2.0", optional = true }

[lints]
workspace = true
