//! Loads adam-lang demo sources and builds a [`Sheet`]/[`Labels`] pair from
//! them. `begin` ships with several example property models (see
//! `assets/*.adm2`); [`available_demos`] lists them and [`load_demo_source`]
//! loads any one of them by name.
//!
//! `toy_example.adm2` demonstrates two independent bidirectional constraint
//! systems (`a × b = c` and `d × e = f`) linked by one conditional on `p`:
//!
//! - `p = 0`: the relationship `c = f` (bidirectional) becomes active.
//! - `p = 1`: the relationship `c = f × 2` (bidirectional) becomes active, alongside a
//!   second, independent relationship `g = c × 10` in the same branch — `g` is *forced*
//!   while this branch is active (see [`adam_rs::Sheet::is_forced`]), so its
//!   Inspector field is disabled and it is highlighted in the graph.
//! - Any other `p`: the two systems are independent and `g` is not forced.
//!
//! `g`'s relationship is its own `relationship { .. }` block within the `1i32` branch,
//! not folded into the `c`/`f` relationship's methods: a relationship's forced outputs
//! are the *intersection* of its methods' pure outputs, so mixing `[c] -> [g]` in with
//! the `c`/`f` methods would make that intersection empty, forcing nothing. A single
//! `conditional` branch can hold any number of `relationship` blocks, each contributing
//! its own independent forced-output set while that branch is active.

use adam_lang::{AdamParser, TypeRegistry};
use adam_rs::Sheet;
use annotate_snippets::Renderer;
use dioxus::prelude::*;
use dioxus_devtools::HotReloadMsg;

use crate::bridge::{Labels, format_adam_error, labels_from_cell_names};

// Generated by build.rs from `assets/*.adm2`: a `DEMO_NAMES: &[&str]` array,
// a `DEMOS_WITH_SOURCE: &[(&str, &str)]` array of (name, embedded source)
// pairs (non-desktop and test builds only), and a `DEMO_ASSETS: &[Asset]`
// array with one `asset!()` registration per file (desktop only). See
// build.rs's own doc comment for why the embedded source is gated out of
// ordinary desktop builds.
include!(concat!(env!("OUT_DIR"), "/demo_manifest.rs"));

/// The currently active demo: its manifest name (used to resolve its asset
/// path and build diagnostic headers) and full source text.
#[derive(Clone, Default)]
pub struct ActiveSource {
    /// The demo's name, as it appears in [`available_demos`] (its filename
    /// stem, e.g. `"toy_example"`).
    pub name: String,
    /// The demo's full adam-lang source text.
    pub text: String,
}

impl ActiveSource {
    /// The `begin/assets/<name>.adm2` path shown in diagnostic headers.
    pub fn file_name(&self) -> String {
        format!("begin/assets/{}.adm2", self.name)
    }
}

/// Lists every demo bundled with `begin`, by name, sorted. A picker UI builds
/// its options from this on every platform; see [`load_demo_source`] for how
/// each name's content actually gets loaded.
pub fn available_demos() -> &'static [&'static str] {
    DEMO_NAMES
}

/// The result of parsing and building a sheet from adam-lang source.
///
/// `sheet_labels` is `None` only on parse failure. A successful parse that
/// then fails to propagate still returns the built sheet and labels alongside
/// the formatted error, matching how the Inspector already tolerates
/// propagate failures during cell edits.
pub struct BuildOutcome {
    /// The built sheet and its UI labels, if parsing succeeded.
    pub sheet_labels: Option<(Sheet, Labels)>,
    /// A formatted rustc-style diagnostic, if parsing or propagation failed.
    pub error: Option<String>,
}

/// Parses `source` as adam-lang, builds a `Sheet` and `Labels`, and propagates
/// once so initial derived values are populated. `file_name` is used only to
/// build diagnostic headers (e.g. `--> begin/assets/toy_example.adm2:8:11`),
/// not to locate `source` itself.
///
/// - Complexity: O(n) in the length of `source` plus the cost of one `propagate()`.
pub fn build_sheet(source: &str, file_name: &str) -> BuildOutcome {
    let mut parser = AdamParser::new(TypeRegistry::new(), cel_parser::OpLookup::new());
    let mut parsed = match parser.parse_str(source) {
        Ok(p) => p,
        Err(e) => {
            let msg = e.format_rustc_style(source, file_name, 1, &Renderer::styled());
            return BuildOutcome {
                sheet_labels: None,
                error: Some(msg),
            };
        }
    };
    let labels = labels_from_cell_names(&parsed.cell_names);
    match parsed.propagate() {
        Ok(()) => {
            parsed.clear_changed();
            BuildOutcome {
                sheet_labels: Some((parsed.sheet, labels)),
                error: None,
            }
        }
        Err(e) => {
            let msg = format_adam_error(&e, source, file_name);
            BuildOutcome {
                sheet_labels: Some((parsed.sheet, labels)),
                error: Some(msg),
            }
        }
    }
}

/// Reads demo `name`'s source directly from its location in the crate source tree.
///
/// This deliberately avoids resolving any [`DEMO_ASSETS`] entry's path at all:
/// `Asset::resolve()` returns the absolute source path directly whenever `begin`
/// isn't running as a bundled app — true for every documented way of running it,
/// always from a live checkout under `dx serve` — so there's nothing to gain from
/// routing through it, and it keeps content loading fully decoupled from
/// `DEMO_ASSETS`' only real purpose: getting `dx` to track and report changes to
/// these files (see [`spawn_hot_reload`]).
///
/// # Errors
///
/// Returns `Err` if the file cannot be read (e.g. a transient race with an
/// editor's save, or `name` matching no file under `assets/`).
#[cfg(feature = "desktop")]
pub fn load_demo_source(name: &str) -> Result<String, String> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(format!("assets/{name}.adm2"));
    std::fs::read_to_string(&path).map_err(|e| format!("failed to read {}: {e}", path.display()))
}

/// Non-desktop fallback: looks `name` up in the compile-time embedded
/// [`DEMOS_WITH_SOURCE`], with no live reload.
///
/// # Errors
///
/// Returns `Err` if `name` doesn't match any embedded demo.
#[cfg(not(feature = "desktop"))]
pub fn load_demo_source(name: &str) -> Result<String, String> {
    DEMOS_WITH_SOURCE
        .iter()
        .find(|&&(n, _)| n == name)
        .map(|&(_, source)| source.to_string())
        .ok_or_else(|| format!("no embedded demo named {name:?}"))
}

/// True if `msg` reports a change to a `.adm2` asset (i.e. any demo source).
///
/// Matches by extension rather than exact path: `dx`'s hot-reload message reports
/// each changed asset as a short, bundled-name path (e.g.
/// `/assets/toy_example.adm2`), which has no reliable equality relationship to any
/// [`DEMO_ASSETS`] entry's resolved path (in a `dx serve` dev session that resolves
/// to the absolute source path instead — see [`load_demo_source`]). Every `.adm2`
/// asset in this crate is a demo source, so matching by extension is both correct
/// and robust to however `dx` names the bundled entry.
///
/// Only called (outside of tests) from [`spawn_hot_reload`], which is desktop-only;
/// unused when the `desktop` feature is disabled, same as [`DEMO_ASSETS`].
///
/// - Complexity: O(n) in the number of changed assets in `msg`.
#[cfg_attr(not(feature = "desktop"), allow(dead_code))]
fn hot_reload_targets_demo(msg: &HotReloadMsg) -> bool {
    msg.assets
        .iter()
        .any(|p| p.extension().and_then(|ext| ext.to_str()) == Some("adm2"))
}

/// Connects to the `dx serve` devserver and calls `on_change` whenever any
/// demo `.adm2` file changes on disk. A no-op if not running under `dx serve`
/// (`dioxus_devtools::connect` itself returns immediately in that case).
///
/// The discarded [`dioxus::asset_resolver::asset_path`] calls below are deliberate,
/// not dead code: `manganis-macro`'s asset registration (unlike its FFI-metadata
/// counterpart) never applies `#[used]` to the linker section holding a
/// [`DEMO_ASSETS`] entry's bundle entry, so if nothing ever reads it, `dx`'s build
/// can legitimately end up with no record of that file to track at all. Touching
/// every entry once here is enough to keep all of them from being compiled away.
///
/// - Complexity: spawns one background OS thread for the life of the process.
#[cfg(feature = "desktop")]
pub fn spawn_hot_reload(mut on_change: impl FnMut() + Send + 'static) {
    for asset in DEMO_ASSETS {
        let _ = dioxus::asset_resolver::asset_path(*asset);
    }
    dioxus_devtools::connect(move |msg| {
        if let dioxus_devtools::DevserverMsg::HotReload(hot_reload) = msg
            && hot_reload_targets_demo(&hot_reload)
        {
            on_change();
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    const VALID_SOURCE: &str = r#"
        sheet s {
            cell a: f64 = 2.0;
            cell b: f64 = 3.0;
            cell c: f64;
            relationship {
                method [a, b] -> [c] { a * b }
                method [b, c] -> [a] { c / b }
                method [a, c] -> [b] { c / a }
            }
        }
    "#;

    #[test]
    fn build_sheet_valid_source_succeeds_with_no_error() {
        let outcome = build_sheet(VALID_SOURCE, "test.adm2");
        assert!(outcome.sheet_labels.is_some());
        assert!(outcome.error.is_none());
    }

    #[test]
    fn build_sheet_parse_error_has_no_sheet_and_formatted_message() {
        let outcome = build_sheet("sheet s { cell x }", "test.adm2");
        assert!(outcome.sheet_labels.is_none());
        let msg = outcome.error.expect("expected a parse error message");
        assert!(msg.contains("error"), "{msg}");
    }

    #[test]
    fn build_sheet_runtime_error_still_returns_sheet_and_message() {
        let source = "sheet s { cell x: i32 = 0; cell y: i32; relationship { method [x] -> [y] { 10i32 / x } } }";
        let outcome = build_sheet(source, "test.adm2");
        assert!(
            outcome.sheet_labels.is_some(),
            "sheet should still be built after a propagate error"
        );
        assert!(outcome.error.is_some());
    }

    #[test]
    fn every_bundled_demo_parses_successfully() {
        for &(name, source) in DEMOS_WITH_SOURCE {
            let outcome = build_sheet(source, &format!("{name}.adm2"));
            assert!(
                outcome.sheet_labels.is_some(),
                "{name} failed to build: {:?}",
                outcome.error
            );
        }
    }

    #[test]
    fn available_demos_is_sorted_and_nonempty() {
        let demos = available_demos();
        assert!(!demos.is_empty());
        let mut sorted = demos.to_vec();
        sorted.sort();
        assert_eq!(demos, sorted);
    }

    #[test]
    fn active_source_file_name_matches_convention() {
        let active = ActiveSource {
            name: "toy_example".to_string(),
            text: String::new(),
        };
        assert_eq!(active.file_name(), "begin/assets/toy_example.adm2");
    }
}

#[cfg(test)]
mod hot_reload_tests {
    use super::*;
    use dioxus_devtools::HotReloadMsg;
    use std::path::PathBuf;

    #[test]
    fn hot_reload_targets_demo_true_for_adm2_asset() {
        let msg = HotReloadMsg {
            assets: vec![PathBuf::from("/assets/toy_example.adm2")],
            ..Default::default()
        };
        assert!(hot_reload_targets_demo(&msg));
    }

    #[test]
    fn hot_reload_targets_demo_true_for_hash_suffixed_adm2_asset() {
        let msg = HotReloadMsg {
            assets: vec![PathBuf::from("/assets/toy_example-a1b2c3d4.adm2")],
            ..Default::default()
        };
        assert!(hot_reload_targets_demo(&msg));
    }

    #[test]
    fn hot_reload_targets_demo_false_when_assets_empty() {
        let msg = HotReloadMsg::default();
        assert!(!hot_reload_targets_demo(&msg));
    }

    #[test]
    fn hot_reload_targets_demo_false_for_unrelated_asset() {
        let msg = HotReloadMsg {
            assets: vec![PathBuf::from("/assets/graph.css")],
            ..Default::default()
        };
        assert!(!hot_reload_targets_demo(&msg));
    }
}
