//! Loads adam-lang example sources and builds a [`Sheet`]/[`Labels`] pair from
//! them. `begin` ships with several example property models (see
//! `examples/*.adm2`); [`available_examples`] lists them and
//! [`load_example_source`] loads any one of them by name.
//!
//! `toy_example.adm2` demonstrates two independent bidirectional constraint
//! systems (`a × b = c` and `d × e = f`) linked by one conditional on `p`:
//!
//! - `p = 0`: the relationship `c = f` (bidirectional) becomes active.
//! - `p = 1`: the relationship `c = f × 2` (bidirectional) becomes active, alongside a
//!   second, independent relationship `g = c × 10` in the same branch — `g` is *forced*
//!   while this branch is active (see [`adam_rs::Sheet::is_forced`]), so its
//!   Inspector field is disabled and it is highlighted in the graph.
//! - Any other `p`: the two systems are independent and `g` is not forced.
//!
//! `g`'s relationship is its own `relationship { .. }` block within the `1i32` branch,
//! not folded into the `c`/`f` relationship's methods: a relationship's forced outputs
//! are the *intersection* of its methods' pure outputs, so mixing `[c] -> [g]` in with
//! the `c`/`f` methods would make that intersection empty, forcing nothing. A single
//! `conditional` branch can hold any number of `relationship` blocks, each contributing
//! its own independent forced-output set while that branch is active.

use adam_lang::{AdamParser, TypeRegistry};
use adam_rs::Sheet;
use annotate_snippets::Renderer;
use dioxus::prelude::*;

use crate::bridge::{Labels, format_adam_error, labels_from_cell_names};

// Generated by build.rs from `examples/*.adm2`: an `EXAMPLES_WITH_SOURCE: &[(&str,
// &str)]` array of (name, embedded source) pairs (non-desktop and test builds only -
// desktop reads both the list and each file's content live from disk instead, see
// `available_examples`/`load_example_source` below). See build.rs's own doc comment
// for why the embedded source is gated out of ordinary desktop builds.
include!(concat!(env!("OUT_DIR"), "/example_manifest.rs"));

/// Identifies where an [`ActiveSource`]'s content came from: a bundled example
/// discovered under `examples/`, or a file the user opened via the "Open…" action.
#[derive(Clone, PartialEq, Eq, Debug, Default)]
pub enum SourceOrigin {
    /// One of [`available_examples`], loaded from `begin/examples/`.
    #[default]
    Example,
    /// A file opened via the "Open…" action.
    ///
    /// Desktop: the real absolute filesystem path, stored losslessly — not a
    /// `Path::display()`-formatted `String`, which replaces invalid UTF-8
    /// with U+FFFD on Unix and so can't be round-tripped back into the exact
    /// same `Path`, breaking reload/re-read for non-UTF-8 paths. Web: the
    /// picked file's name only — browsers never expose a real filesystem
    /// path, and a browser-supplied name is always valid UTF-8 anyway.
    Opened(std::ffi::OsString),
}

/// The currently active source: its display name, full text, and where it
/// came from (a bundled example or a user-opened file) — see [`SourceOrigin`].
#[derive(Clone, Default)]
pub struct ActiveSource {
    /// Display label: the example's name (its filename stem) or the opened
    /// file's name.
    pub name: String,
    /// The source's full adam-lang source text.
    pub text: String,
    /// Where this source came from.
    pub origin: SourceOrigin,
}

impl ActiveSource {
    /// The path shown in diagnostic headers: `begin/examples/<name>.adm2` for a
    /// bundled example, or the opened file's real path/name directly (lossily
    /// converted to UTF-8 for this display string only — the stored
    /// `OsString` itself stays lossless for reload; see [`SourceOrigin::Opened`]).
    pub fn file_name(&self) -> String {
        match &self.origin {
            SourceOrigin::Example => format!("begin/examples/{}.adm2", self.name),
            SourceOrigin::Opened(path) => path.to_string_lossy().into_owned(),
        }
    }
}

/// This crate's bundled `examples/` directory, resolved relative to
/// `CARGO_MANIFEST_DIR` so it's found regardless of the process's current
/// working directory.
///
/// - Complexity: O(1).
#[cfg(feature = "desktop")]
fn examples_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("examples")
}

/// Lists every `.adm2` file directly under `dir`, by name (filename stem),
/// sorted. A missing or unreadable `dir` yields an empty list rather than an
/// error — [`available_examples`] has nothing sensible to fall back to.
///
/// - Complexity: O(n log n) in the number of entries under `dir`.
#[cfg(feature = "desktop")]
fn scan_examples_dir(dir: &std::path::Path) -> Vec<String> {
    let mut names: Vec<String> = std::fs::read_dir(dir)
        .map(|entries| {
            entries
                .filter_map(|entry| entry.ok())
                .filter_map(|entry| {
                    let path = entry.path();
                    if path.extension().and_then(|e| e.to_str()) == Some("adm2") {
                        path.file_stem()
                            .and_then(|s| s.to_str())
                            .map(|s| s.to_string())
                    } else {
                        None
                    }
                })
                .collect()
        })
        .unwrap_or_default();
    names.sort();
    names
}

/// Lists every example bundled with `begin`, by name, sorted. A picker UI
/// builds its options from this; see [`load_example_source`] for how each
/// name's content actually gets loaded.
///
/// - Complexity: on desktop, O(n log n) in the number of files under
///   `examples/` — a fresh directory scan on every call, so the result
///   always reflects the current directory contents (not cached). Otherwise
///   O(n log n) in [`EXAMPLES_WITH_SOURCE`]'s length.
pub fn available_examples() -> Vec<String> {
    #[cfg(feature = "desktop")]
    {
        scan_examples_dir(&examples_dir())
    }
    #[cfg(not(feature = "desktop"))]
    {
        let mut names: Vec<String> = EXAMPLES_WITH_SOURCE
            .iter()
            .map(|&(name, _)| name.to_string())
            .collect();
        names.sort();
        names
    }
}

/// The result of parsing and building a sheet from adam-lang source.
///
/// `sheet_labels` is `None` only on parse failure. A successful parse that
/// then fails to propagate still returns the built sheet and labels alongside
/// the formatted error, matching how the Inspector already tolerates
/// propagate failures during cell edits.
pub struct BuildOutcome {
    /// The built sheet and its UI labels, if parsing succeeded.
    pub sheet_labels: Option<(Sheet, Labels)>,
    /// A formatted rustc-style diagnostic, if parsing or propagation failed.
    pub error: Option<String>,
}

/// Builds an [`cel_parser::OpLookup`] with the CEL standard library installed, so every
/// adam-lang source `begin` parses — bundled examples and test sources alike — has the
/// same function set (`min`, `max`, `clamp`, etc.) available.
fn op_lookup() -> cel_parser::OpLookup {
    let mut lookup = cel_parser::OpLookup::new();
    cel_std::install(&mut lookup);
    lookup
}

/// Parses `source` as adam-lang, builds a `Sheet` and `Labels`, and propagates
/// once so initial derived values are populated. `file_name` is used only to
/// build diagnostic headers (e.g. `--> begin/examples/toy_example.adm2:8:11`),
/// not to locate `source` itself.
///
/// - Complexity: O(n) in the length of `source` plus the cost of one `propagate()`.
pub fn build_sheet(source: &str, file_name: &str) -> BuildOutcome {
    let mut parser = AdamParser::new(TypeRegistry::new(), op_lookup());
    let mut parsed = match parser.parse_str(source) {
        Ok(p) => p,
        Err(e) => {
            let msg = e.format_rustc_style(source, file_name, 1, &Renderer::styled());
            return BuildOutcome {
                sheet_labels: None,
                error: Some(msg),
            };
        }
    };
    let labels = labels_from_cell_names(&parsed.cell_names);
    match parsed.propagate() {
        Ok(()) => {
            parsed.clear_changed();
            BuildOutcome {
                sheet_labels: Some((parsed.sheet, labels)),
                error: None,
            }
        }
        Err(e) => {
            let msg = format_adam_error(&e, source, file_name);
            BuildOutcome {
                sheet_labels: Some((parsed.sheet, labels)),
                error: Some(msg),
            }
        }
    }
}

/// Reads example `name`'s source directly from its location in the crate source tree.
///
/// # Errors
///
/// Returns `Err` if `name` contains a path separator or `..` (rejected before
/// touching the filesystem, so it can't resolve outside `examples/`), or if
/// the file cannot be read (e.g. a transient race with an editor's save).
#[cfg(feature = "desktop")]
pub fn load_example_source(name: &str) -> Result<String, String> {
    if name.contains('/') || name.contains('\\') || name.contains("..") {
        return Err(format!("invalid example name {name:?}"));
    }
    let path = examples_dir().join(format!("{name}.adm2"));
    std::fs::read_to_string(&path).map_err(|e| format!("failed to read {}: {e}", path.display()))
}

/// Non-desktop fallback: looks `name` up in the compile-time embedded
/// [`EXAMPLES_WITH_SOURCE`], with no live reload.
///
/// # Errors
///
/// Returns `Err` if `name` doesn't match any embedded example.
#[cfg(not(feature = "desktop"))]
pub fn load_example_source(name: &str) -> Result<String, String> {
    EXAMPLES_WITH_SOURCE
        .iter()
        .find(|&&(n, _)| n == name)
        .map(|&(_, source)| source.to_string())
        .ok_or_else(|| format!("no embedded example named {name:?}"))
}

/// Watches `dir` for changes, calling `on_change` on every filesystem event —
/// a file created, removed, or modified directly under `dir`. The returned
/// watcher must be kept alive for as long as the watch should remain active —
/// dropping it stops watching.
///
/// # Errors
///
/// Returns `Err` if the underlying OS watch could not be established (e.g.
/// `dir` doesn't exist).
#[cfg(feature = "desktop")]
fn spawn_watch_on_dir(
    dir: std::path::PathBuf,
    mut on_change: impl FnMut() + Send + 'static,
) -> notify::Result<notify::RecommendedWatcher> {
    use notify::Watcher;

    let mut watcher = notify::recommended_watcher(move |res: notify::Result<notify::Event>| {
        if res.is_ok() {
            on_change();
        }
    })?;
    watcher.watch(&dir, notify::RecursiveMode::NonRecursive)?;
    Ok(watcher)
}

/// Watches `begin/examples/` for changes — a file added, removed, or edited —
/// calling `on_change` on every event. The returned watcher must be kept
/// alive for as long as the watch should remain active.
///
/// Replaces this crate's previous `dx-serve`-devserver-dependent hot reload:
/// this watches the real filesystem directly, so it reacts to *any* change
/// (including a file appearing or disappearing) and works whether or not
/// `dx serve` happens to be running.
///
/// # Errors
///
/// Returns `Err` if the underlying OS watch could not be established.
#[cfg(feature = "desktop")]
pub fn spawn_examples_watch(
    on_change: impl FnMut() + Send + 'static,
) -> notify::Result<notify::RecommendedWatcher> {
    spawn_watch_on_dir(examples_dir(), on_change)
}

#[cfg(test)]
mod tests {
    use super::*;

    const VALID_SOURCE: &str = r#"
        sheet s {
            cell a: f64 = 2.0;
            cell b: f64 = 3.0;
            cell c: f64;
            relationship {
                method [a, b] -> [c] { a * b }
                method [b, c] -> [a] { c / b }
                method [a, c] -> [b] { c / a }
            }
        }
    "#;

    #[test]
    fn build_sheet_valid_source_succeeds_with_no_error() {
        let outcome = build_sheet(VALID_SOURCE, "test.adm2");
        assert!(outcome.sheet_labels.is_some());
        assert!(outcome.error.is_none());
    }

    #[test]
    fn build_sheet_parse_error_has_no_sheet_and_formatted_message() {
        let outcome = build_sheet("sheet s { cell x }", "test.adm2");
        assert!(outcome.sheet_labels.is_none());
        let msg = outcome.error.expect("expected a parse error message");
        assert!(msg.contains("error"), "{msg}");
    }

    #[test]
    fn build_sheet_runtime_error_still_returns_sheet_and_message() {
        let source = "sheet s { cell x: i32 = 0; cell y: i32; relationship { method [x] -> [y] { 10i32 / x } } }";
        let outcome = build_sheet(source, "test.adm2");
        assert!(
            outcome.sheet_labels.is_some(),
            "sheet should still be built after a propagate error"
        );
        assert!(outcome.error.is_some());
    }

    #[test]
    fn every_bundled_example_parses_successfully() {
        for &(name, source) in EXAMPLES_WITH_SOURCE {
            let outcome = build_sheet(source, &format!("{name}.adm2"));
            assert!(
                outcome.sheet_labels.is_some(),
                "{name} failed to build: {:?}",
                outcome.error
            );
        }
    }

    #[test]
    fn image_resize_constrain_is_relevant_despite_only_being_a_conditional_expression_input() {
        // Regression test: `constrain` is never itself a relationship output or a plain
        // match cell — it's one of two inputs to `conditional resample && constrain`'s match
        // expression. `Sheet::contributing_cells` must still trace through every expression
        // input to find it, or it wrongly shows as an irrelevant/disabled field even though
        // editing it changes which branch is active.
        use adam_lang::AdamParser;
        let source = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("examples/image_resize.adm2"),
        )
        .unwrap();
        let mut parser = AdamParser::new(TypeRegistry::new(), op_lookup());
        let mut parsed = parser.parse_str(&source).unwrap();
        parsed.propagate().unwrap();
        let (constrain_id, _) = *parsed.cell_names.get("constrain").unwrap();
        assert!(parsed.output_relevant_cells().contains(&constrain_id));
    }

    #[test]
    fn image_resize_relevance_does_not_depend_on_which_cell_currently_holds_strength() {
        // Regression test: `width_pixels`/`width_percent`/`doc_width_inches`/
        // `doc_resolution` form a strength-ambiguous diamond (any two determine the rest).
        // In the default state, `width_pixels` and `doc_resolution` happen to be the
        // strength-chosen sources — but every cell in the diamond, plus every cell feeding a
        // conditional match subject (`resample` and `constrain` are both inputs to one
        // conditional's match expression; `auto_quality` is a plain match cell), must show as
        // relevant regardless of which specific cells the *current* strengths picked.
        use adam_lang::AdamParser;
        let source = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("examples/image_resize.adm2"),
        )
        .unwrap();
        let mut parser = AdamParser::new(TypeRegistry::new(), op_lookup());
        let mut parsed = parser.parse_str(&source).unwrap();
        parsed.propagate().unwrap();
        let relevant = parsed.output_relevant_cells();
        for name in [
            "width_pixels",
            "width_percent",
            "doc_width_inches",
            "doc_resolution",
            "original_width",
            "resample",
            "constrain",
            "auto_quality",
            "screen_lpi",
        ] {
            let (id, _) = *parsed.cell_names.get(name).unwrap();
            assert!(relevant.contains(&id), "{name} should be relevant");
        }
    }

    #[test]
    #[cfg(feature = "desktop")]
    fn load_example_source_rejects_name_containing_parent_dir_reference() {
        // Resolves (via `..`) to the same real file as "toy_example", but must
        // still be rejected rather than trusting whatever `fs::read_to_string`
        // happens to resolve.
        let sneaky = "toy_example/../toy_example";
        assert!(load_example_source(sneaky).is_err());
    }

    #[test]
    #[cfg(feature = "desktop")]
    fn load_example_source_rejects_name_containing_path_separator() {
        assert!(load_example_source("sub/toy_example").is_err());
        assert!(load_example_source("sub\\toy_example").is_err());
    }

    #[test]
    fn available_examples_is_sorted_and_nonempty() {
        let examples = available_examples();
        assert!(!examples.is_empty());
        let mut sorted = examples.clone();
        sorted.sort();
        assert_eq!(examples, sorted);
    }

    #[test]
    #[cfg(feature = "desktop")]
    fn scan_examples_dir_reflects_current_directory_contents() {
        let dir = std::env::temp_dir().join("begin_example_source_test_scan_examples_dir");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir(&dir).unwrap();
        std::fs::write(dir.join("zeta.adm2"), "sheet s {}").unwrap();
        std::fs::write(dir.join("alpha.adm2"), "sheet s {}").unwrap();
        std::fs::write(dir.join("ignored.txt"), "not an example").unwrap();

        let names = scan_examples_dir(&dir);

        std::fs::remove_dir_all(&dir).unwrap();
        assert_eq!(names, vec!["alpha".to_string(), "zeta".to_string()]);
    }

    #[test]
    fn active_source_file_name_example_matches_convention() {
        let active = ActiveSource {
            name: "toy_example".to_string(),
            text: String::new(),
            origin: SourceOrigin::Example,
        };
        assert_eq!(active.file_name(), "begin/examples/toy_example.adm2");
    }

    #[test]
    fn active_source_file_name_opened_returns_path_directly() {
        let active = ActiveSource {
            name: "my_model".to_string(),
            text: String::new(),
            origin: SourceOrigin::Opened("/home/user/models/my_model.adm2".into()),
        };
        assert_eq!(active.file_name(), "/home/user/models/my_model.adm2");
    }

    #[test]
    fn active_source_file_name_opened_is_lossy_for_non_utf8_path() {
        #[cfg(unix)]
        {
            use std::os::unix::ffi::OsStringExt;
            // 0xFF is not valid UTF-8 on its own; to_string_lossy() must
            // replace it with U+FFFD rather than panicking or truncating.
            let non_utf8 = std::ffi::OsString::from_vec(vec![0xFF, b'.', b'a', b'd', b'm', b'2']);
            let active = ActiveSource {
                name: "weird".to_string(),
                text: String::new(),
                origin: SourceOrigin::Opened(non_utf8),
            };
            assert_eq!(active.file_name(), "\u{FFFD}.adm2");
        }
    }
}

#[cfg(all(test, feature = "desktop"))]
mod watch_tests {
    use super::*;
    use std::sync::mpsc;
    use std::time::Duration;

    #[test]
    fn spawn_watch_on_dir_fires_on_new_file() {
        let dir = std::env::temp_dir().join("begin_example_source_test_watch_new_file");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir(&dir).unwrap();

        let (tx, rx) = mpsc::channel::<()>();
        let _watcher = spawn_watch_on_dir(dir.clone(), move || {
            let _ = tx.send(());
        })
        .unwrap();

        std::fs::write(dir.join("new_example.adm2"), "sheet s {}").unwrap();

        let fired = rx.recv_timeout(Duration::from_secs(5)).is_ok();
        std::fs::remove_dir_all(&dir).unwrap();
        assert!(
            fired,
            "watcher should fire when a file is created in the watched directory"
        );
    }

    #[test]
    fn spawn_watch_on_dir_fires_on_removed_file() {
        let dir = std::env::temp_dir().join("begin_example_source_test_watch_removed_file");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir(&dir).unwrap();
        let file = dir.join("goes_away.adm2");
        std::fs::write(&file, "sheet s {}").unwrap();

        let (tx, rx) = mpsc::channel::<()>();
        let _watcher = spawn_watch_on_dir(dir.clone(), move || {
            let _ = tx.send(());
        })
        .unwrap();

        std::fs::remove_file(&file).unwrap();

        let fired = rx.recv_timeout(Duration::from_secs(5)).is_ok();
        std::fs::remove_dir_all(&dir).unwrap();
        assert!(
            fired,
            "watcher should fire when a file is removed from the watched directory"
        );
    }
}
