[package]
name = "cel-runtime"
version = "0.1.0"
edition = "2024"
description = "A stack-based runtime for developing domain specific languages"

[dependencies]
anyhow = "1.0"
typenum = "1.20.1"

[dev-dependencies]
adam-rs = { path = "../adam-rs" }

[features]
playground = []

[lints]
workspace = true
