[package]
name = "ez-adam"
version = "0.1.0"
edition = "2024"
description = "Standalone visual editor for adam-rs property models"

[dependencies]
slotmap = { version = "1.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cel-parser = { path = "../cel-parser" }
cel-std = { path = "../cel-std" }

[dev-dependencies]
adam-lang = { path = "../adam-lang" }

[lints]
workspace = true
